title: Srinath Menon
description: > # this means to ignore newlines until "baseurl:"
  A personal exploration space
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Srinath Menon # add your name
author-img: Sri_128px.jpg # add your photo
about-author: A Digital Product Mgr by profession, a Web Design Enthusiast and a Lifelong Learner  # add description
social-twitter: wereboss # add your Twitter handle
social-facebook: srinath.menon.718 # add your Facebook handle
social-github: wereboss # add your Github handle
social-linkedin: srinath-menon-b5b5971 # add your Linkedin handle
social-email: me@srinathmenon.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
